version: "3.9"

services:
  front:
    image: sermalenk/skypro-front:lesson-34
    ports:
      - "8000:80"
    depends_on:
      - api
  api:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    volumes:
      - ./.docker_env:/todolist/.env
  migrations:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    #    volumes:
    #      - ./.docker_env:/app/.env
    command: python manage.py migrate
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: todolist
      POSTGRES_PASSWORD: todolist
      POSTGRES_DB: todolist
      POSTGRES_HOST: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U todolist"]
      interval: 5s
      timeout: 5s
      retries: 15
    volumes:
      - ./postgres-data:/var/lib/postgresql/data 700
