version: "3.8"

services:
  front:
    image: sermalenk/skypro-front:lesson-36
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_started
  api:
    image: dvasilevich/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    environment:
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_HOST: postgres
    env_file:
      - .env
    volumes:
      - ./.docker_env:/api/.env
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  migrations:
    image: dvasilevich/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./.docker_env:/api/.env
    command: python manage.py migrate

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER -d $DB_NAME"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: