version: "3.8"

services:
  front:
    image: sermalenk/skypro-front:lesson-38
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api

  api:
    image: dvasilevich/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    environment:
      DB_HOST: postgres
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      TOKEN: $BOT_TOKEN
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    env_file: .env

  bot:
    image: dvasilevich/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    environment:
      DB_HOST: postgres
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      TOKEN: $BOT_TOKEN
    ports:
      - "443:443"
    depends_on:
      postgres:
        condition: service_started
      migrations:
        condition: service_completed_successfully
      api:
        condition: service_started
    env_file: .env
    command: python manage.py runbot

  migrations:
    image: dvasilevich/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    environment:
      DB_HOST: postgres
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    command: python manage.py migrate

  postgres:
    image: postgres:14.6-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $DB_USER -d $DB_NAME"]
      interval: 5s
      timeout: 5s
      retries: 15
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
