version: "3.8"

services:
  front:
    image: sermalenk/skypro-front:lesson-38
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_started
  api:
    image: dvasilevich/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    environment:
      DB_HOST: postgres
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      BOT_TOKEN: $BOT_TOKEN
      SOCIAL_AUTH_VK_OAUTH2_KEY: $SOCIAL_AUTH_VK_OAUTH2_KEY
      SOCIAL_AUTH_VK_OAUTH2_SECRET: $SOCIAL_AUTH_VK_OAUTH2_SECRET
    volumes:
      - ./.docker_env:/api/.env
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  bot:
    image: dvasilevich/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    environment:
      DB_HOST: postgres
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      BOT_TOKEN: $BOT_TOKEN
    ports:
      - "443:443"
    depends_on:
      postgres:
        condition: service_started
      migrations:
        condition: service_completed_successfully
      api:
        condition: service_started
    volumes:
      - ./.docker_env:/api/.env
    command: python manage.py runbot


  migrations:
#    image: dvasilevich/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
    volumes:
      - ./.docker_env:/api/.env
    command: python manage.py migrate

  postgres:
    image: postgres:14.6-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER -d $DB_NAME"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: